"""Disk accounting for the SuppOrth home directory.

Three predictors, each with its own source checkout, its own Python packages
and a profile database, add up to gigabytes. Most of that is genuinely needed,
but a fair share is not: build trees left behind after compilation, checkouts
of refs that are no longer installed, and temporary directories from runs that
were interrupted. None of it is visible without knowing where to look, so it
accumulates silently and the user finds out from their disk, not from us.

This module names what is there and what can go.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from . import manifest, paths

# Directories a predictor's build leaves behind and never reads again.
BUILD_ARTIFACTS = ("build", ".eggs", ".mypy_cache", ".pytest_cache")

# Temporary directories predictors create mid-task and delete on success, so a
# surviving one means the task was interrupted and its contents are partial.
INTERRUPTED = ("tmp-indexing", "tmp_indexing")


@dataclass
class Entry:
    """A directory and what it costs."""

    label: str
    path: Path
    size: int


@dataclass
class Reclaimable:
    """Something that can be deleted, and the consequence of deleting it."""

    path: Path
    size: int
    reason: str
    # What is lost. "nothing" is regenerated by the tool itself on next use;
    # "refetch" costs a download or a rebuild to get back.
    cost: str = "nothing"


def directory_size(path: Path) -> int:
    if not path.exists():
        return 0
    total = 0
    for item in path.rglob("*"):
        try:
            if item.is_file() and not item.is_symlink():
                total += item.stat().st_size
        except OSError:
            continue
    return total


def human(size: int) -> str:
    value = float(size)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            return f"{value:.0f} {unit}" if unit in {"B", "KB"} else f"{value:.1f} {unit}"
        value /= 1024
    return f"{value:.1f} TB"


def usage() -> list[Entry]:
    """Where the space in the home directory has gone, largest first."""
    entries: list[Entry] = []
    tools = paths.tools_root()
    if tools.exists():
        for tool_dir in sorted(tools.iterdir()):
            if tool_dir.is_dir():
                entries.append(Entry(tool_dir.name, tool_dir, directory_size(tool_dir)))
    for extra in (paths.shared_bin(), paths.cache_root()):
        if extra.exists():
            entries.append(Entry(extra.name, extra, directory_size(extra)))
    return sorted(entries, key=lambda e: e.size, reverse=True)


def installed_roots() -> set[Path]:
    """The checkout each predictor is actually installed from."""
    roots: set[Path] = set()
    for record in manifest.load()["predictors"].values():
        root = record.get("root")
        if root:
            roots.add(Path(root).resolve())
    return roots


def reclaimable() -> list[Reclaimable]:
    """Everything under the home directory that can go without breaking a tool."""
    found: list[Reclaimable] = []
    tools = paths.tools_root()
    if not tools.exists():
        return found

    live = installed_roots()
    for tool_dir in sorted(tools.iterdir()):
        if not tool_dir.is_dir():
            continue
        for checkout in sorted(tool_dir.iterdir()):
            if not checkout.is_dir():
                continue

            # A checkout of a ref that is not the installed one: left over from
            # installing, then reinstalling at a different ref.
            if checkout.resolve() not in live:
                found.append(
                    Reclaimable(
                        checkout,
                        directory_size(checkout),
                        f"{tool_dir.name} checkout at '{checkout.name}', which is not the installed ref",
                        cost="refetch",
                    )
                )
                continue

            for name in BUILD_ARTIFACTS:
                candidate = checkout / name
                if candidate.is_dir():
                    found.append(
                        Reclaimable(
                            candidate,
                            directory_size(candidate),
                            f"{tool_dir.name} build tree, already compiled and installed",
                        )
                    )
            for temp in INTERRUPTED:
                for candidate in checkout.rglob(temp):
                    if candidate.is_dir():
                        found.append(
                            Reclaimable(
                                candidate,
                                directory_size(candidate),
                                f"{tool_dir.name} temporary directory from an interrupted task",
                            )
                        )
            found.extend(_predictor_leftovers(tool_dir.name, checkout))

    return sorted(found, key=lambda item: item.size, reverse=True)


def _predictor_leftovers(name: str, checkout: Path) -> list[Reclaimable]:
    """Ask a predictor which of its own artefacts it has abandoned."""
    from . import adapters

    try:
        adapter = adapters.get(name)
    except Exception:  # noqa: BLE001 - a directory need not correspond to an adapter
        return []
    return [
        Reclaimable(
            path,
            path.stat().st_size if path.is_file() else directory_size(path),
            reason,
        )
        for path, reason in adapter.leftovers(checkout)
    ]


def remove(items: list[Reclaimable]) -> int:
    """Delete the given items, returning the bytes freed."""
    freed = 0
    for item in items:
        try:
            if item.path.is_dir():
                shutil.rmtree(item.path)
            else:
                item.path.unlink()
        except OSError:
            continue
        freed += item.size
    return freed


def prune_build_artifacts(root: Path) -> int:
    """Drop a checkout's build tree once it has been installed."""
    freed = 0
    for name in BUILD_ARTIFACTS:
        candidate = root / name
        if candidate.is_dir():
            size = directory_size(candidate)
            try:
                shutil.rmtree(candidate)
            except OSError:
                continue
            freed += size
    return freed
